const getters = {
    productInfo: state => state.app.productInfo,
    sidebar: state => state.app.sidebar,
    language: state => state.app.language,
    size: state => state.app.size,
    device: state => state.app.device,
    visitedViews: state => state.tagsView.visitedViews,
    cachedViews: state => state.tagsView.cachedViews,
    token: state => state.user.token,
    avatar: state => state.user.avatar,
    name: state => state.user.name,
    introduction: state => state.user.introduction,
    userInfo: state => state.user.userInfo,
    userCardInfo: state => state.user.userCardInfo,
    groupInfo: state => state.user.getGroupInfo,
    auth: state => state.user.auth,
    roles: state => state.user.roles,
    realName: state => state.user.realName,
    userName: state => state.user.userName,
    permission_routes: state => state.permission.routes,
    errorLogs: state => state.errorLog.logs,
    term_id: state => state.lesson.term_id,
    term: state => state.lesson.term,
    weekData: state => state.lesson.weekData,
    courseArray: state => state.lesson.courseArray
}
export default getters
